version: '3.9'

#MySQl
services:
  app-db:
    image: mysql:8
    container_name: docker-mysql
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --collation-server=utf8mb4_0900_bin
      - --transaction-isolation=READ-COMMITTED
    restart: always
    #のちにenvファイルから読み込むようにする
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}
    ports:
      - "3307:3306" #3007につなぐ。ホストの 3307 でアクセスすると、コンテナの 3306（MySQL標準）に接続される
    
    #データ永続化、よく分からん。永続化コメアウトで接続確認ok
    #volumes:
     # - ./data:/var/lib/mysql/data


#ボリューム削除コマンド
# docker-compose down -v
#停止
# docker-compose- stop/start
#コンテナ再起動
# docker-compose up -d
#ログ確認
# docker logs -f app-db
#接続コマンド
# mysql -h 127.0.0.1 -P 3307 -u root -p
#MySQL終了
#exit
